// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '01ref&reactive': typeof import('./src/components/01ref&reactive/index.vue')['default']
    '02computed$watch': typeof import('./src/components/02computed$watch/index.vue')['default']
    03hook: typeof import('./src/components/03hook/index.vue')['default']
    '04shallowReactive&shallowRef': typeof import('./src/components/04shallowReactive&shallowRef/index.vue')['default']
    '05toRaw&markRaw': typeof import('./src/components/05toRaw&markRaw/index.vue')['default']
    06customRef: typeof import('./src/components/06customRef/index.vue')['default']
    07shopList: typeof import('./src/components/07shopList/index.vue')['default']
    '08生命周期': typeof import('./src/components/08生命周期/index.vue')['default']
    '09组件布局练习': typeof import('./src/components/09组件布局练习/index.vue')['default']
    '10父子组件传参': typeof import('./src/components/10父子组件传参/index.vue')['default']
    '11全局和递归组件': typeof import('./src/components/11全局和递归组件/index.vue')['default']
    '12插槽': typeof import('./src/components/12插槽/index.vue')['default']
    '13异步组件和传送组件': typeof import('./src/components/13异步组件和传送组件/index.vue')['default']
    '14keepAlive和动画组件': typeof import('./src/components/14keep-alive和动画组件/index.vue')['default']
    15transitionGroup: typeof import('./src/components/15transitionGroup/index.vue')['default']
    '16组件通信': typeof import('./src/components/16组件通信/index.vue')['default']
    17TSX: typeof import('./src/components/17TSX/index.vue')['default']
    '18深入vModel': typeof import('./src/components/18深入v-model/index.vue')['default']
    '19vue3指令': typeof import('./src/components/19vue3指令/index.vue')['default']
    '20自定义hook': typeof import('./src/components/20自定义hook/index.vue')['default']
    '21全局属性和自定义插件': typeof import('./src/components/21全局属性和自定义插件/index.vue')['default']
    '21引入elementUi&样式选择器': typeof import('./src/components/21引入element-ui&样式选择器/index.vue')['default']
    '22原子化css': typeof import('./src/components/22原子化css/index.vue')['default']
    '23移动端自适应': typeof import('./src/components/23移动端自适应/index.vue')['default']
    '24unocss原子化': typeof import('./src/components/24unocss原子化/index.vue')['default']
    '25函数式变成': typeof import('./src/components/25函数式变成/index.vue')['default']
    A: typeof import('./src/components/11全局和递归组件/components/A.vue')['default']
    A_21: typeof import('./src/components/21引入element-ui&样式选择器/A_21.vue')['default']
    AsyncCom: typeof import('./src/components/13异步组件和传送组件/components/AsyncCom.vue')['default']
    B: typeof import('./src/components/11全局和递归组件/components/B.vue')['default']
    C: typeof import('./src/components/11全局和递归组件/components/C.vue')['default']
    Card: typeof import('./src/components/11全局和递归组件/components/Card.vue')['default']
    Content: typeof import('./src/components/09组件布局练习/components/content.vue')['default']
    D: typeof import('./src/components/16组件通信/components/D.vue')['default']
    Dialog: typeof import('./src/components/12插槽/components/Dialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Menubar: typeof import('./src/components/09组件布局练习/components/menubar.vue')['default']
    Navbar: typeof import('./src/components/09组件布局练习/components/navbar.vue')['default']
    Sub: typeof import('./src/components/08生命周期/Sub.vue')['default']
    TreeList: typeof import('./src/components/11全局和递归组件/components/TreeList.vue')['default']
  }
}
