// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '01ref&reactive': typeof import('./src/components/01ref&reactive/index.vue')['default']
    '02computed$watch': typeof import('./src/components/02computed$watch/index.vue')['default']
    03hook: typeof import('./src/components/03hook/index.vue')['default']
    '04shallowReactive&shallowRef': typeof import('./src/components/04shallowReactive&shallowRef/index.vue')['default']
    '05toRaw&markRaw': typeof import('./src/components/05toRaw&markRaw/index.vue')['default']
    06customRef: typeof import('./src/components/06customRef/index.vue')['default']
    07shopList: typeof import('./src/components/07shopList/index.vue')['default']
    '08生命周期': typeof import('./src/components/08生命周期/index.vue')['default']
    '09组件布局练习': typeof import('./src/components/09组件布局练习/index.vue')['default']
    '10父子组件传参': typeof import('./src/components/10父子组件传参/index.vue')['default']
    '11全局和递归组件': typeof import('./src/components/11全局和递归组件/index.vue')['default']
    '12插槽': typeof import('./src/components/12插槽/index.vue')['default']
    '13异步组件和传送组件': typeof import('./src/components/13异步组件和传送组件/index.vue')['default']
    '14keepAlive和动画组件': typeof import('./src/components/14keep-alive和动画组件/index.vue')['default']
    15transitionGroup: typeof import('./src/components/15transitionGroup/index.vue')['default']
    '16组件传参': typeof import('./src/components/16组件传参/index.vue')['default']
    '16组件通信': typeof import('./src/components/16组件通信/index.vue')['default']
    17TSX: typeof import('./src/components/17TSX/index.vue')['default']
    A: typeof import('./src/components/11全局和递归组件/components/A.vue')['default']
    AsyncCom: typeof import('./src/components/13异步组件和传送组件/components/AsyncCom.vue')['default']
    B: typeof import('./src/components/11全局和递归组件/components/B.vue')['default']
    C: typeof import('./src/components/11全局和递归组件/components/C.vue')['default']
    Card: typeof import('./src/components/11全局和递归组件/components/Card.vue')['default']
    Content: typeof import('./src/components/09组件布局练习/components/content.vue')['default']
    D: typeof import('./src/components/16组件通信/components/D.vue')['default']
    Dialog: typeof import('./src/components/12插槽/components/Dialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Menubar: typeof import('./src/components/09组件布局练习/components/menubar.vue')['default']
    Navbar: typeof import('./src/components/09组件布局练习/components/navbar.vue')['default']
    Sub: typeof import('./src/components/08生命周期/Sub.vue')['default']
    TreeList: typeof import('./src/components/11全局和递归组件/components/TreeList.vue')['default']
  }
}
